Repository CA-G12/Fashionista-Store, pull requests merged in 2022-09, with the labels that each got.

#5 create file structure
  fashionista/.gitignore
  fashionista/README.md
  fashionista/client/.gitignore
  fashionista/client/README.md
  fashionista/client/package-lock.json
  fashionista/client/package.json
  fashionista/client/public/favicon.ico
  fashionista/client/public/index.html
  fashionista/client/public/logo192.png
  fashionista/client/public/logo512.png
  fashionista/client/public/manifest.json
  fashionista/client/public/robots.txt
  fashionista/client/src/App.css
  fashionista/client/src/App.js
  fashionista/client/src/App.test.js
  fashionista/client/src/index.css
  fashionista/client/src/index.js
  fashionista/client/src/logo.svg
  fashionista/client/src/reportWebVitals.js
  fashionista/client/src/setupTests.js
  fashionista/package-lock.json
  fashionista/package.json
  fashionista/server/app.js
  fashionista/server/controllers/authController.js
  fashionista/server/controllers/index.js
  fashionista/server/controllers/userController.js
  fashionista/server/database/config/build.js
  fashionista/server/database/config/build.sql
  fashionista/server/database/config/connection.js
  fashionista/server/database/queries/queries.js
  fashionista/server/errors/customError.js
  fashionista/server/middlewares/errorHandler.js
  fashionista/server/middlewares/index.js
  fashionista/server/middlewares/verifyToken.js
  fashionista/server/routes/authRoutes.js
  fashionista/server/routes/index.js
  fashionista/server/routes/userRoutes.js
  fashionista/server/server.js
  fashionista/server/tests/database.test.js
  fashionista/server/tests/routes.test.js
Labels: approved

#7 server setup
  .gitignore
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
  fashionista/README.md
  fashionista/client/README.md
  fashionista/server/database/config/build.sql
  fashionista/server/database/queries/queries.js
  package-lock.json
  package.json
  server/app.js
  server/controllers/authController.js
  server/controllers/index.js
  server/controllers/userController.js
  server/database/config/build.js
  server/database/config/build.sql
  server/database/config/connection.js
  server/database/queries/queries.js
  server/errors/customError.js
  server/index.js
  server/middlewares/errorHandler.js
  server/middlewares/index.js
  server/middlewares/verifyToken.js
  server/routes/authRoutes.js
  server/routes/index.js
  server/routes/userRoutes.js
  server/tests/database.test.js
  server/tests/routes.test.js
Labels: approved

#8 edit cross-env from devdep to dep
  package.json
Labels: awating-review

#9 create DB schema
  server/database/config/build.sql
  server/database/config/seeder.sql
Labels: awating-review

#10 adding figma link to readme file
  README.md
Labels: awating-review

#12 eslint-prettier configs
  .eslintrc.js
  .prettierrc
  .prettierrc.json
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  package-lock.json
  package.json
  server/app.js
Labels: awating-review

#14 adding components folder
  client/public/Components/cart/.gitkeep
  client/public/Components/index.js
  client/public/Components/landingPage/.gitkeep
  client/public/Components/login/.gitkeep
  client/public/Components/productDetails/.gitkeep
  client/public/Components/signup/.gitkeep
Labels: awating-review

#16 moving components folder to src
  client/src/Components/cart/.gitkeep
  client/src/Components/index.js
  client/src/Components/landingPage/.gitkeep
  client/src/Components/login/.gitkeep
  client/src/Components/productDetails/.gitkeep
  client/src/Components/signup/.gitkeep
Labels: Done

#19 fix eslint
  .eslintrc.js
  .vscode/settings.json
  client/.eslintrc.js
  client/src/App.js
  client/src/index.js
  client/src/reportWebVitals.js
Labels: Approved

#21 17 add proxy
  client/package.json
  client/src/App.js
  server/app.js
Labels: Approved

#23 20 login button components
  .prettierrc
  client/.eslintrc.js
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/Components/button/Button.js
  client/src/Components/login/Login.js
  client/src/Components/login/cartIcon.png
  client/src/index.js
  client/src/logo.svg
  client/src/reportWebVitals.js
  client/src/setupTests.js
  server/app.js
Labels: Awating-review

#26 style folder
  client/src/style/.gitkeep
Labels: Approved

#30 create product card
  client/.eslintrc.js
  client/src/Components/landingPage/card/Card.js
  client/src/style/Card.css
Labels: Awating-review

#36 product details component
  client/src/Components/datails/Details.js
  client/src/style/details.css
Labels: Awating-review

#38 create initial router
  client/.eslintrc.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/landingPage/.gitkeep
  client/src/Components/landingPage/card/Card.js
  client/src/Components/landingPage/landing.jsx
Labels: Approved

#39 correct props name
  client/src/Components/landingPage/card/Card.js
Labels: Approved

#41 edit style for filter section and card
  client/package-lock.json
  client/package.json
  client/src/Components/landingPage/Filters/PriceFilter.jsx
  client/src/Components/landingPage/landing.jsx
  client/src/style/FilterCategory.css
  client/src/style/PriceFilter.css
Labels: Awating-review

#43 fix landing design
  client/src/Components/landingPage/landing.jsx
  client/src/style/FilterCategory.css
Labels: Approved

#44 27 create navbar
  client/src/Components/nav/Navbar.jsx
  client/src/index.css
Labels: Awating-review

#46 handle auth
  client/src/Components/landingPage/card/Card.js
  client/src/Components/landingPage/landing.jsx
  server/app.js
Labels: Approved

#50 handle filter category
  client/src/Components/landingPage/Filters/CategoryFilter.jsx
  client/src/Components/landingPage/card/Card.js
  client/src/Components/landingPage/landing.jsx
  server/app.js
Labels: Awating-review

#48 47 details comp
  client/src/Components/datails/Details.js
  client/src/Components/landingPage/card/Card.js
  client/src/Components/landingPage/landing.jsx
  client/src/style/Card.css
  client/src/style/details.css
Labels: Awating-review

#53 create details page from components
  client/src/App.js
  client/src/Components/cart/.gitkeep
  client/src/Components/cart/Cart.js
  client/src/Components/datails/DetailPage.js
  client/src/Components/landingPage/landing.jsx
Labels: Awating-review

#56 add price filter and fix eslint
  client/.eslintrc.js
  client/src/App.js
  client/src/Components/button/Button.js
  client/src/Components/datails/Details.js
  client/src/Components/landingPage/Filters/PriceFilter.jsx
  client/src/Components/landingPage/card/Card.js
  client/src/Components/landingPage/landing.jsx
  client/src/Components/login/Login.js
  client/src/Components/signup/Signup.js
  client/src/index.js
Labels: Awating-review

#59 git checkout to previous merge
  client/src/Components/nav/Navbar.jsx
  client/src/style/button.css
Labels: Awating-review

#61 fix eslint errors
  .eslintrc.js
  .prettierrc.json
  package.json
  server/app.js
  server/database/config/build.js
  server/database/config/connection.js
  server/errors/customError.js
  server/index.js
  server/middlewares/errorHandler.js
Labels: Done

#72 handle sending and fetching datain sign up form
  client/src/App.js
  client/src/Components/landingPage/landing.jsx
  client/src/Components/nav/Navbar.jsx
  client/src/Components/signup/Signup.js
  server/controllers/authController.js
  server/controllers/userController.js
  server/controllers/users/setUser.js
  server/routes/authRoutes.js
Labels: Approved

#73 handle login
  server/controllers/index.js
  server/controllers/users/getUser.js
  server/controllers/users/index.js
  server/database/config/connection.js
  server/database/queries/index.js
  server/database/queries/users/getUserQuery.js
  server/database/queries/users/index.js
  server/errors/customError.js
  server/routes/userRoutes.js
Labels: Awating-review

#74 66 crud card backend
  client/src/App.js
  client/src/Components/cart/Cart.js
  client/src/Components/datails/DetailPage.js
  client/src/Components/signup/Signup.js
  server/app.js
  server/controllers/cart/addCartItem.js
  server/controllers/cart/deleteCartItem.js
  server/controllers/cart/getCartItems.js
  server/controllers/cart/index.js
  server/controllers/cart/updateCartItemQuantity.js
  server/controllers/index.js
  server/controllers/products/getProducts.js
  server/controllers/products/index.js
  server/controllers/users/getUser.js
  server/controllers/users/index.js
  server/controllers/users/setUser.js
  server/database/config/connection.js
  server/database/queries/cart/addCartItem.js
  server/database/queries/cart/deleteCartItem.js
  server/database/queries/cart/getCartItemsByUserId.js
  server/database/queries/cart/index.js
  server/database/queries/cart/updateQuantity.js
  server/database/queries/index.js
  server/database/queries/products/getProducts.js
  server/database/queries/products/index.js
  server/database/queries/queries.js
  server/database/queries/users/getUserQuery.js
  server/database/queries/users/index.js
  server/database/queries/users/setUser.js
  server/errors/customError.js
  server/routes/cartItemsRoutes.js
  server/routes/index.js
  server/routes/productsRoutes.js
Labels: Awating-review

#79 handle search by name route
  server/controllers/index.js
  server/controllers/products/getProducts.js
  server/controllers/products/getProductsByName.js
  server/controllers/products/index.js
  server/database/config/connection.js
  server/database/queries/index.js
  server/database/queries/products/getProductsByName.js
  server/database/queries/products/index.js
  server/routes/productsRoutes.js
Labels: Approved

#84 handle add to cart
  client/src/Components/button/Button.js
  client/src/Components/cart/Cart.js
  client/src/Components/landingPage/card/Card.js
  client/src/Components/nav/Navbar.jsx
  client/src/style/Card.css
  client/src/style/cart.css
  server/controllers/cart/getCartItems.js
  server/database/queries/cart/addCartItem.js
Labels: Awating-review

#88 handle product details front and back
  client/src/App.js
  client/src/Components/datails/DetailPage.js
  client/src/Components/datails/Details.js
  client/src/Components/landingPage/card/Card.js
  server/controllers/index.js
  server/controllers/products/getProductById.js
  server/controllers/products/index.js
  server/database/queries/index.js
  server/database/queries/products/getProductById.js
  server/database/queries/products/index.js
  server/routes/productsRoutes.js
Labels: Approved

#90 89 handle token login signup
  client/src/Components/landingPage/landing.jsx
  client/src/Components/login/Login.js
  client/src/Components/signup/Signup.js
  server/controllers/module/checkUserAuth.js
  server/controllers/module/generateToken.js
  server/controllers/module/verifyTokenjs.js
  server/controllers/users/getUser.js
  server/controllers/users/setUser.js
  server/routes/userRoutes.js
Labels: Awating-review

#95 91 buy button
  client/src/App.js
  client/src/Components/card/Card.js
  client/src/Components/cart/Cart.js
  client/src/Components/datails/DetailPage.js
  client/src/Components/datails/Details.js
  client/src/Components/landingPage/landing.jsx
  client/src/Components/login/Login.js
  client/src/Components/nav/Navbar.jsx
  client/src/Components/products/ProductsPage.jsx
  client/src/Components/signup/Signup.js
  client/src/index.css
  client/src/style/details.css
  server/app.js
  server/controllers/cart/addCartItem.js
  server/controllers/cart/deleteAllItems.js
  server/controllers/cart/getCartItems.js
  server/controllers/cart/getTotalPrice.js
  server/controllers/cart/index.js
  server/controllers/cart/updateCartItemQuantity.js
  server/controllers/index.js
  server/controllers/module/checkUserAuth.js
  server/controllers/module/generateToken.js
  server/controllers/module/verifyTokenjs.js
  server/controllers/products/getProductById.js
  server/controllers/products/getProducts.js
  server/controllers/products/getProductsByName.js
  server/controllers/products/getProductsByPrice.js
  server/controllers/products/index.js
  server/controllers/users/getUser.js
  server/controllers/users/setUser.js
  server/database/queries/cart/deleteAllItemsQuery.js
  server/database/queries/cart/index.js
  server/database/queries/cart/totalPriceQuery.js
  server/database/queries/index.js
  server/database/queries/products/getProductById.js
  server/database/queries/products/getProducts.js
  server/database/queries/products/getProductsCount.js
  server/database/queries/products/index.js
  server/database/queries/users/getUserQuery.js
  server/routes/cartItemsRoutes.js
  server/routes/productsRoutes.js
  server/routes/userRoutes.js
Labels: Awating-review
